### PR TITLE
fix(intl-locales-support): fix #35, fix TS support for intl-locales-support

### LINKED ISSUE #35: [intl-locales-supported] typescript error "index.ts" is not a module
### Which package?
intl-locales-supported

### Is this a BUG REPORT or FEATURE REQUEST? (choose one)
bug

### Expected behavior

no TS errors

### Current behavior
TS error: `node_modules/intl-locales-supported/index.ts' is not a module`;

### Step to reproduce for BUG REPORT
```ts
import areIntlLocalesSupported from 'intl-locales-supported';
```

### Your Environment
TS 3.4.5

### PR DESCRIPTION
**Pull request by longlho**

### CODE REVIEW

**Comment by longlho** [comment]
@ipanasenko do u mind verifying this fix?

**Review by redonkulus — APPROVED** [review]

**Comment by ipanasenko** [comment]
Hi. I've installed v1.0.3 and now I receive error `Module not found: Can't resolve './lib' in '/node_modules/intl-locales-supported'`. Maybe you forgot to add `files` key to `package.json`?

**Comment by longlho** [comment]
@ipanasenko `1.0.5` should fix that I believe

**Comment by ipanasenko** [comment]
Yes, it works now. Thanks!

**Pull request merged**
